[package]
name = "yesno-operator"
description = "Kubernetes operator for yesnodb clusters"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
crc32c.workspace = true
futures = "0.3"
jiff = "0.2"
k8s-openapi = { version = "0.28", features = ["v1_36", "schemars"] }
kube = { version = "4.2", features = ["derive", "runtime"] }
pem = "3"
ring = "0.17"
schemars = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
thiserror.workspace = true
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal"] }
tonic = { version = "0.14", features = ["tls-ring"] }
tracing.workspace = true
tracing-subscriber = { version = "0.3", default-features = false, features = [
    "ansi",
    "env-filter",
    "fmt",
] }
yesno-server = { path = "../yesno-server" }

[dev-dependencies]
toml = "0.9"
