//! The foreign data wrapper: one yesno key as a one-column `bigint` table.
//!
//! # Entry points are raw C functions, not `#[pg_extern]`
//!
//! `fdw_handler` and `fdw_validator` are pseudo-types PostgreSQL resolves by
//! symbol name, so both are `#[no_mangle] extern "C-unwind"` with a hand-written
//! `pg_finfo_` record — the same `PG_FUNCTION_INFO_V1` protocol `#[pg_extern]`
//! generates, spelled out because the return types have no Rust equivalent for
//! the macro to map.
//!
//! **Every one of them carries `#[pg_guard]`, and that is not decoration.** A
//! Rust panic unwinding across the C boundary corrupts PostgreSQL's state; the
//! guard converts it into a PostgreSQL `ERROR` the backend can recover from. A
//! callback without it is a backend crash, and these callbacks run inside the
//! planner and the executor where a crash takes the whole session with it.

pub mod import;
pub mod join;
pub mod modify;
pub mod qual;
pub mod scan;
pub mod upper;
pub mod walk;

use pgrx::prelude::*;
use pgrx::PgBox;

use crate::options::{OptionError, ServerOptions, TableOptions};

/// Emit the `PG_FUNCTION_INFO_V1` record for a hand-written C entry point.
///
/// `#[pg_extern]` does this automatically; these two functions cannot use it,
/// so the record is written out. Removing one produces an extension that
/// creates cleanly and fails at first call with "could not find function",
/// because PostgreSQL resolves the symbol lazily.
/// Written out rather than generated by a macro: `pgrx` does not re-export
/// `paste`, and concatenating an identifier in a `macro_rules!` is not possible
/// without it. Two functions is cheaper than the dependency.
const V1_API: pg_sys::Pg_finfo_record = pg_sys::Pg_finfo_record { api_version: 1 };

#[no_mangle]
#[doc(hidden)]
pub extern "C" fn pg_finfo_yesno_fdw_handler() -> &'static pg_sys::Pg_finfo_record {
    &V1_API
}

#[no_mangle]
#[doc(hidden)]
pub extern "C" fn pg_finfo_yesno_fdw_validator() -> &'static pg_sys::Pg_finfo_record {
    &V1_API
}

/// Returns the `FdwRoutine` PostgreSQL dispatches through.
///
/// The routine is `palloc`'d as a proper `Node` — `T_FdwRoutine` — because
/// PostgreSQL copies and inspects it as one.
///
/// Only the seven scan callbacks are populated. The rest stay `None`, which
/// is how PostgreSQL learns the wrapper is read-only and cannot push down a
/// join or an aggregate: it checks the pointer before calling. Filling one in
/// before its phase is implemented would advertise a capability that is not
/// there, and the planner would take it.
#[pg_guard]
#[no_mangle]
pub extern "C-unwind" fn yesno_fdw_handler(_fcinfo: pg_sys::FunctionCallInfo) -> pg_sys::Datum {
    let mut routine =
        unsafe { PgBox::<pg_sys::FdwRoutine>::alloc_node(pg_sys::NodeTag::T_FdwRoutine) };

    routine.GetForeignRelSize = Some(scan::get_foreign_rel_size);
    routine.GetForeignPaths = Some(scan::get_foreign_paths);
    routine.GetForeignPlan = Some(scan::get_foreign_plan);
    routine.BeginForeignScan = Some(scan::begin_foreign_scan);
    routine.IterateForeignScan = Some(scan::iterate_foreign_scan);
    routine.ReScanForeignScan = Some(scan::rescan_foreign_scan);
    routine.EndForeignScan = Some(scan::end_foreign_scan);
    routine.ExplainForeignScan = Some(scan::explain_foreign_scan);
    routine.GetForeignUpperPaths = Some(upper::get_foreign_upper_paths);
    routine.GetForeignJoinPaths = Some(join::get_foreign_join_paths);

    // Writes. `ExecForeignUpdate` stays `None`: `IsForeignRelUpdatable` does
    // not advertise UPDATE, and `PlanForeignModify` rejects it with a message
    // saying why.
    routine.ImportForeignSchema = Some(import::import_foreign_schema);
    routine.IsForeignRelUpdatable = Some(modify::is_foreign_rel_updatable);
    routine.AddForeignUpdateTargets = Some(modify::add_foreign_update_targets);
    routine.PlanForeignModify = Some(modify::plan_foreign_modify);
    routine.BeginForeignModify = Some(modify::begin_foreign_modify);
    routine.ExecForeignInsert = Some(modify::exec_foreign_insert);
    routine.ExecForeignDelete = Some(modify::exec_foreign_delete);
    routine.EndForeignModify = Some(modify::end_foreign_modify);

    pg_sys::Datum::from(routine.into_pg())
}

/// Validate the options of a `SERVER`, `FOREIGN TABLE` or `USER MAPPING`.
///
/// This is what turns `OPTIONS ( endpiont '…' )` into an error at `CREATE`
/// time rather than a default that quietly takes effect on the first query.
/// PostgreSQL passes the catalog OID so one validator can serve every object
/// kind the wrapper participates in.
#[pg_guard]
#[no_mangle]
pub extern "C-unwind" fn yesno_fdw_validator(fcinfo: pg_sys::FunctionCallInfo) -> pg_sys::Datum {
    // The first argument is a `text[]` of `name=value` strings, **not** a
    // `List *`. `untransformRelOptions` is what turns it into the `DefElem`
    // list every FDW validator in the tree works with; skipping it and casting
    // the datum to `List *` compiles and then reads arbitrary memory.
    //
    // SAFETY: `fcinfo` is PostgreSQL's, and `fdw_validator`'s signature is
    // `(text[], oid)`, so both accessors are in range and correctly typed.
    let opts = unsafe {
        let raw = pgrx::fcinfo::pg_getarg_datum_raw(fcinfo, 0);
        def_elems_to_pairs(pg_sys::untransformRelOptions(raw))
    };
    let catalog: pg_sys::Oid = unsafe { pgrx::fcinfo::pg_getarg::<pg_sys::Oid>(fcinfo, 1) }
        .expect("fdw_validator's catalog argument is never NULL");

    let result = match catalog {
        pg_sys::ForeignServerRelationId => ServerOptions::parse(&opts).map(|_| ()),
        pg_sys::ForeignTableRelationId => TableOptions::parse(&opts).map(|_| ()),
        // A user mapping carries no options in v1. Anything present is a typo,
        // and reporting it beats ignoring it.
        pg_sys::UserMappingRelationId => match opts.first() {
            None => Ok(()),
            Some((name, _)) => Err(OptionError::Unknown {
                catalog: "USER MAPPING",
                name: name.clone(),
            }),
        },
        // `FOREIGN DATA WRAPPER` itself, and anything else PostgreSQL adds
        // later. No options are defined, so accept an empty list and reject
        // the rest rather than silently allowing everything.
        _ => match opts.first() {
            None => Ok(()),
            Some((name, _)) => Err(OptionError::Unknown {
                catalog: "FOREIGN DATA WRAPPER",
                name: name.clone(),
            }),
        },
    };

    if let Err(e) = result {
        // `ereport` at ERROR does not return; the guard is what makes the
        // longjmp safe from Rust.
        error!("{e}");
    }

    pg_sys::Datum::from(0)
}

/// Convert PostgreSQL's `List *` of `DefElem` into plain `(name, value)` pairs.
///
/// The conversion lives here so that every *rule* about what a valid option set
/// is stays in [`crate::options`], where it can be unit-tested without a
/// backend.
///
/// # Safety
///
/// `list` must be a `List *` of `DefElem *`, which is what PostgreSQL passes to
/// an FDW validator.
pub(crate) unsafe fn relation_options(list: *mut pg_sys::List) -> Vec<(String, String)> {
    unsafe { def_elems_to_pairs(list) }
}

/// # Safety
///
/// `list` must be a `List *` of `DefElem *`.
unsafe fn def_elems_to_pairs(list: *mut pg_sys::List) -> Vec<(String, String)> {
    let mut out = Vec::new();
    if list.is_null() {
        return out;
    }
    // Walked directly rather than through `pgrx::PgList`, which lives behind
    // pgrx's `cshim` feature — disabled here, because enabling it adds a C
    // compilation step to the build for one convenience wrapper. Since
    // PostgreSQL 13 a `List` is array-backed, so this is an index rather than a
    // pointer chase.
    let len = unsafe { (*list).length } as usize;
    let cells = unsafe { (*list).elements };
    for i in 0..len {
        // SAFETY: `i < length`, and `untransformRelOptions` returns a list whose
        // cells are `DefElem *`.
        let def = unsafe { (*cells.add(i)).ptr_value } as *mut pg_sys::DefElem;
        if def.is_null() {
            continue;
        }
        let name = unsafe { core::ffi::CStr::from_ptr((*def).defname) }
            .to_string_lossy()
            .into_owned();
        // `defGetString` rather than reading `arg` directly: it handles every
        // `Node` shape a value can arrive as and raises a proper error for one
        // that has none, which is what an option with no `=` produces.
        let value = unsafe { core::ffi::CStr::from_ptr(pg_sys::defGetString(def)) }
            .to_string_lossy()
            .into_owned();
        out.push((name, value));
    }
    out
}
