"""Python client for yesnodb over Apache Arrow Flight."""

from .errors import ExpressionError, ProtocolError, TicketError, YesnoError
from .expression import (
    MAGIC,
    MAX_DEPTH,
    MAX_NODES,
    ORDINAL_LIMIT,
    QUERY_MAGIC,
    QUERY_VERSION,
    VERSION,
    And,
    AndNot,
    Empty,
    Key,
    Literal,
    Or,
    QueryRequest,
    Range,
    SetExpr,
    ViewExpand,
    ViewFold,
    ViewLayout,
    ViewReduce,
    ViewSelect,
    ViewSpec,
    complement,
    xor,
)
from .flight import (
    BATCH_ROWS,
    ORDINAL_SCHEMA,
    PAIR_SCHEMA,
    Ack,
    Client,
    QueryInfo,
    QueryStream,
    ServerStats,
    TLSConfig,
)
from .ticket import TICKET_HEADER_LEN, Ticket

__all__ = [
    "BATCH_ROWS",
    "MAGIC",
    "MAX_DEPTH",
    "MAX_NODES",
    "ORDINAL_LIMIT",
    "ORDINAL_SCHEMA",
    "PAIR_SCHEMA",
    "QUERY_MAGIC",
    "QUERY_VERSION",
    "TICKET_HEADER_LEN",
    "VERSION",
    "Ack",
    "And",
    "AndNot",
    "Client",
    "Empty",
    "ExpressionError",
    "Key",
    "Literal",
    "Or",
    "ProtocolError",
    "QueryInfo",
    "QueryRequest",
    "QueryStream",
    "Range",
    "ServerStats",
    "SetExpr",
    "TLSConfig",
    "Ticket",
    "TicketError",
    "ViewExpand",
    "ViewFold",
    "ViewLayout",
    "ViewReduce",
    "ViewSelect",
    "ViewSpec",
    "YesnoError",
    "complement",
    "xor",
]
